/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:41f9a463-c00a-4985-a730-5d11570c1e31",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AsRS7OCLv",
    "aws_user_pools_web_client_id": "3tgc2ca94pd4ldtjsri9jngl1e",
    "oauth": {}
};


export default awsmobile;
